CREATE TABLE accounts."SavingsBuckets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "AccountId" integer NOT NULL,
    "Name" text NOT NULL,
    "AllocatedAmount" numeric NOT NULL,
    "TargetAmount" numeric,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_SavingsBuckets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavingsBuckets_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SavingsBuckets_AccountId" ON accounts."SavingsBuckets" ("AccountId");
