CREATE TABLE transactions."Merchants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" text NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Merchants" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Merchants_UserId_Name" ON transactions."Merchants" ("UserId", "Name");

CREATE TABLE transactions."MerchantAliases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MerchantId" integer NOT NULL,
    "Alias" text NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_MerchantAliases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MerchantAliases_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES transactions."Merchants" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MerchantAliases_MerchantId" ON transactions."MerchantAliases" ("MerchantId");

ALTER TABLE transactions."Transactions" ADD COLUMN "MerchantId" integer;

CREATE INDEX "IX_Transactions_MerchantId" ON transactions."Transactions" ("MerchantId");

ALTER TABLE transactions."Transactions" ADD CONSTRAINT "FK_Transactions_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES transactions."Merchants" ("Id") ON DELETE SET NULL;
