CREATE TABLE accounts."Goals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" text NOT NULL,
    "TargetAmount" numeric NOT NULL,
    "TargetDate" timestamp with time zone,
    "IsAchieved" boolean NOT NULL DEFAULT false,
    "SavingsBucketId" integer,
    "ManualCurrentAmount" numeric NOT NULL DEFAULT 0,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Goals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Goals_SavingsBuckets_SavingsBucketId" FOREIGN KEY ("SavingsBucketId") REFERENCES accounts."SavingsBuckets" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Goals_UserId" ON accounts."Goals" ("UserId");
CREATE INDEX "IX_Goals_SavingsBucketId" ON accounts."Goals" ("SavingsBucketId");
