CREATE TABLE accounts."CreditCardBills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" text NOT NULL,
    "AccountId" integer NOT NULL,
    "StatementDate" timestamp with time zone NOT NULL,
    "BillAmount" numeric(18,2) NOT NULL,
    "MinimumDue" numeric(18,2) NULL,
    "DueDate" timestamp with time zone NULL,
    "IsPaid" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_CreditCardBills_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CreditCardBills_AccountId_StatementDate" ON accounts."CreditCardBills" ("AccountId", "StatementDate");
