

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'accounts') THEN
            CREATE SCHEMA accounts;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'transactions') THEN
            CREATE SCHEMA transactions;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE accounts."AccountCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "UserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AccountCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE accounts."AccountCategoryLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer NOT NULL,
        "OldData" text,
        "NewData" text,
        "Action" text NOT NULL,
        "ChangedByUserId" text NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AccountCategoryLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE accounts."AccountLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer NOT NULL,
        "OldData" text,
        "NewData" text,
        "Action" text NOT NULL,
        "ChangedByUserId" text NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AccountLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."Roles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE transactions."TransactionCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "UserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TransactionCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE transactions."TransactionCategoryLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer NOT NULL,
        "OldData" text,
        "NewData" text,
        "Action" text NOT NULL,
        "ChangedByUserId" text NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TransactionCategoryLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE transactions."TransactionLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer NOT NULL,
        "OldData" text,
        "NewData" text,
        "Action" text NOT NULL,
        "ChangedByUserId" text NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TransactionLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."Users" (
        "Id" text NOT NULL,
        "Name" text NOT NULL,
        "DateOfBirth" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE accounts."Accounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Balance" numeric NOT NULL,
        "UserId" text NOT NULL,
        "AccountCategoryId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Accounts_AccountCategories_AccountCategoryId" FOREIGN KEY ("AccountCategoryId") REFERENCES accounts."AccountCategories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."UserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE identity."UserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE TABLE transactions."Transactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Description" text NOT NULL,
        "Amount" numeric NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Type" integer NOT NULL,
        "AccountId" integer NOT NULL,
        "TransactionCategoryId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Transactions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Transactions_TransactionCategories_TransactionCategoryId" FOREIGN KEY ("TransactionCategoryId") REFERENCES transactions."TransactionCategories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE UNIQUE INDEX "IX_AccountCategories_UserId_Name" ON accounts."AccountCategories" ("UserId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_Accounts_AccountCategoryId" ON accounts."Accounts" ("AccountCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON identity."RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON identity."Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE UNIQUE INDEX "IX_TransactionCategories_UserId_Name" ON transactions."TransactionCategories" ("UserId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_Transactions_AccountId" ON transactions."Transactions" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_Transactions_TransactionCategoryId" ON transactions."Transactions" ("TransactionCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON identity."UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON identity."UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON identity."UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE INDEX "EmailIndex" ON identity."Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251003074053_FinalSchemaWithAuditingv1') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON identity."Users" ("NormalizedUserName");
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251004153519_AddFeedbackAndLoggingFeatures') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'feedback') THEN
            CREATE SCHEMA feedback;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251004153519_AddFeedbackAndLoggingFeatures') THEN
    CREATE TABLE feedback."FeedbackLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer NOT NULL,
        "OldData" text,
        "NewData" text,
        "Action" text NOT NULL,
        "ChangedByUserId" text NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FeedbackLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251004153519_AddFeedbackAndLoggingFeatures') THEN
    CREATE TABLE feedback."Feedbacks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Email" text NOT NULL,
        "Type" text NOT NULL,
        "Description" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113070002_AddRefreshTokens') THEN
    ALTER TABLE transactions."TransactionCategories" ADD "IsTransferCategory" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE identity."Users" ADD "CurrentSessionId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE identity."Users" ADD "LastKnownIp" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE identity."Users" ADD "LastKnownUserAgent" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE identity."Users" ADD "LastLoginTime" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE identity."Users" ADD "LastSeenUtc" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE transactions."Transactions" ADD "DataHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE transactions."TransactionLogs" ADD "LogHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE transactions."TransactionCategoryLogs" ADD "LogHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE feedback."FeedbackLogs" ADD "LogHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE accounts."Accounts" ADD "DataHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE accounts."AccountLogs" ADD "LogHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    ALTER TABLE accounts."AccountCategoryLogs" ADD "LogHash" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106100307_InitialCreate') THEN
    CREATE TABLE identity."RefreshTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "Token" text NOT NULL,
        "ExpiresUtc" timestamp with time zone NOT NULL,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "CreatedByIp" text NOT NULL,
        "RevokedUtc" timestamp with time zone,
        "RevokedByIp" text,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("UserId", "Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    DROP INDEX transactions."IX_Transactions_AccountId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE transactions."Transactions" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE transactions."Transactions" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE transactions."TransactionCategories" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE transactions."TransactionCategories" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE feedback."Feedbacks" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE feedback."Feedbacks" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE accounts."Accounts" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE accounts."Accounts" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE accounts."AccountCategories" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE accounts."AccountCategories" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    CREATE INDEX "IX_Transactions_AccountId_Date" ON transactions."Transactions" ("AccountId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306162916_Phase1_DB_Upgrades') THEN
    ALTER TABLE transactions."Transactions" ADD CONSTRAINT "CK_Transaction_Amount_Positive" CHECK ("Amount" > 0);
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306164553_Phase2_Budgets') THEN
    CREATE TABLE "Budgets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "TransactionCategoryId" integer,
        "Amount" numeric(18,2) NOT NULL,
        "Period" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Budget_Amount" CHECK ("Amount" > 0),
        CONSTRAINT "FK_Budgets_TransactionCategories_TransactionCategoryId" FOREIGN KEY ("TransactionCategoryId") REFERENCES transactions."TransactionCategories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Budgets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306164553_Phase2_Budgets') THEN
    CREATE INDEX "IX_Budgets_TransactionCategoryId" ON "Budgets" ("TransactionCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306164553_Phase2_Budgets') THEN
    CREATE INDEX "IX_Budgets_UserId_TransactionCategoryId" ON "Budgets" ("UserId", "TransactionCategoryId");
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308065116_Phase2_RecurringTransactions') THEN
    CREATE TABLE transactions."RecurringTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "AccountId" integer NOT NULL,
        "TransactionCategoryId" integer,
        "Description" text NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Type" integer NOT NULL,
        "Frequency" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "NextProcessDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastProcessedDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_RecurringTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RecurringTransaction_Amount_Positive" CHECK ("Amount" > 0),
        CONSTRAINT "FK_RecurringTransactions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RecurringTransactions_TransactionCategories_TransactionCate~" FOREIGN KEY ("TransactionCategoryId") REFERENCES transactions."TransactionCategories" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308065116_Phase2_RecurringTransactions') THEN
    CREATE INDEX "IX_RecurringTransactions_AccountId" ON transactions."RecurringTransactions" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308065116_Phase2_RecurringTransactions') THEN
    CREATE INDEX "IX_RecurringTransactions_TransactionCategoryId" ON transactions."RecurringTransactions" ("TransactionCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308065116_Phase2_RecurringTransactions') THEN
    CREATE INDEX "IX_RecurringTransactions_UserId_NextProcessDate_IsActive" ON transactions."RecurringTransactions" ("UserId", "NextProcessDate", "IsActive");
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN

                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='transactions' AND table_name='Transactions' AND column_name='UserId') THEN
                            ALTER TABLE transactions."Transactions" ADD COLUMN "UserId" text;
                        END IF;
                    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    UPDATE transactions."Transactions" SET "UserId" = 'system' WHERE "UserId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN

                    DO $$
                    BEGIN
                        ALTER TABLE transactions."Transactions" ALTER COLUMN "UserId" SET NOT NULL;
                        ALTER TABLE transactions."Transactions" ALTER COLUMN "UserId" SET DEFAULT '';
                    EXCEPTION WHEN OTHERS THEN
                        -- Ignore if already configured
                    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE TABLE "IssueTaxonomies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "Type" text NOT NULL,
        "ParentId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueTaxonomies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueTaxonomies_IssueTaxonomies_ParentId" FOREIGN KEY ("ParentId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE TABLE transactions."Subscriptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "Name" text NOT NULL,
        "Tag" text,
        "CancellationUrl" text,
        "RecurringTransactionId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Subscriptions_RecurringTransactions_RecurringTransactionId" FOREIGN KEY ("RecurringTransactionId") REFERENCES transactions."RecurringTransactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE TABLE "Issues" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Status" text NOT NULL,
        "Priority" text NOT NULL,
        "CategoryId" integer,
        "SubcategoryId" integer,
        "Severity" text NOT NULL,
        "ImpactsMoney" boolean NOT NULL,
        "FinancialImpactAmount" numeric,
        "Frequency" text NOT NULL,
        "TrustPenalty" integer NOT NULL,
        "Votes" integer NOT NULL,
        "PainScore" double precision NOT NULL,
        "CreatorUserId" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Issues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Issues_IssueTaxonomies_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Issues_IssueTaxonomies_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE TABLE "IssueComments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IssueId" integer NOT NULL,
        "Content" text NOT NULL,
        "CreatorUserId" text,
        "ExpectedBehavior" text,
        "ActualBehavior" text,
        "HasWorkaround" boolean NOT NULL,
        "StructuredMetadata" text,
        "IsHelpful" boolean NOT NULL,
        "IsRootCause" boolean NOT NULL,
        "IsReproConfirmed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueComments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE INDEX IF NOT EXISTS "IX_Transactions_UserId" ON transactions."Transactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE INDEX "IX_IssueComments_IssueId" ON "IssueComments" ("IssueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE INDEX "IX_Issues_CategoryId" ON "Issues" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE INDEX "IX_Issues_SubcategoryId" ON "Issues" ("SubcategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE INDEX "IX_IssueTaxonomies_ParentId" ON "IssueTaxonomies" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE UNIQUE INDEX "IX_Subscriptions_RecurringTransactionId" ON transactions."Subscriptions" ("RecurringTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515074348_AddUserIdToTransaction') THEN
    CREATE UNIQUE INDEX "IX_Subscriptions_UserId_Name" ON transactions."Subscriptions" ("UserId", "Name");
    END IF;
END $EF$;





DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519080424_AddIssueVotes') THEN
    CREATE TABLE "IssueVotes" (
        "IssueId" integer NOT NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_IssueVotes" PRIMARY KEY ("IssueId", "UserId"),
        CONSTRAINT "FK_IssueVotes_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    ALTER TABLE "IssueVotes" ADD "Value" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    ALTER TABLE "IssueComments" ADD "ParentCommentId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    ALTER TABLE "IssueComments" ADD "Score" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    CREATE TABLE "CommentVotes" (
        "CommentId" integer NOT NULL,
        "UserId" text NOT NULL,
        "Value" integer NOT NULL,
        CONSTRAINT "PK_CommentVotes" PRIMARY KEY ("CommentId", "UserId"),
        CONSTRAINT "FK_CommentVotes_IssueComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "IssueComments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    CREATE INDEX "IX_IssueComments_ParentCommentId" ON "IssueComments" ("ParentCommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519095253_AddCommentVotesAndReplies') THEN
    ALTER TABLE "IssueComments" ADD CONSTRAINT "FK_IssueComments_IssueComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "IssueComments" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519102104_AddIssueTypeField') THEN
    ALTER TABLE "Issues" ADD "Type" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD "ClosedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD "ClosedByUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD "GitHubIssueUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD "IsClosed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD "MilestoneId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE TABLE "CommentReactions" (
        "CommentId" integer NOT NULL,
        "UserId" text NOT NULL,
        "Emoji" text NOT NULL,
        CONSTRAINT "PK_CommentReactions" PRIMARY KEY ("CommentId", "UserId", "Emoji"),
        CONSTRAINT "FK_CommentReactions_IssueComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "IssueComments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE TABLE "IssueAssignees" (
        "IssueId" integer NOT NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_IssueAssignees" PRIMARY KEY ("IssueId", "UserId"),
        CONSTRAINT "FK_IssueAssignees_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE TABLE "IssueLabels" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Color" text NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueLabels" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE TABLE "IssueMilestones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text,
        "DueDate" timestamp with time zone,
        "IsClosed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueMilestones" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE TABLE "IssueLabelAssignments" (
        "IssueId" integer NOT NULL,
        "LabelId" integer NOT NULL,
        CONSTRAINT "PK_IssueLabelAssignments" PRIMARY KEY ("IssueId", "LabelId"),
        CONSTRAINT "FK_IssueLabelAssignments_IssueLabels_LabelId" FOREIGN KEY ("LabelId") REFERENCES "IssueLabels" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_IssueLabelAssignments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE INDEX "IX_Issues_MilestoneId" ON "Issues" ("MilestoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE INDEX "IX_IssueLabelAssignments_LabelId" ON "IssueLabelAssignments" ("LabelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    CREATE UNIQUE INDEX "IX_IssueLabels_Name" ON "IssueLabels" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519103216_AddPhase2Features') THEN
    ALTER TABLE "Issues" ADD CONSTRAINT "FK_Issues_IssueMilestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES "IssueMilestones" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    ALTER TABLE "Issues" ADD "AcknowledgedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    ALTER TABLE "Issues" ADD "ResolvedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE TABLE "Badges" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "IconUrl" text,
        "Color" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Badges" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE TABLE "IssueAttachments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IssueId" integer NOT NULL,
        "FileName" text NOT NULL,
        "FilePath" text NOT NULL,
        "ContentType" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "UploadedByUserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueAttachments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE TABLE "UserGamificationProfiles" (
        "UserId" text NOT NULL,
        "KarmaScore" integer NOT NULL,
        "ContributorTag" text,
        CONSTRAINT "PK_UserGamificationProfiles" PRIMARY KEY ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE TABLE "UserBadges" (
        "UserId" text NOT NULL,
        "BadgeId" integer NOT NULL,
        "AwardedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserBadges" PRIMARY KEY ("UserId", "BadgeId"),
        CONSTRAINT "FK_UserBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE UNIQUE INDEX "IX_Badges_Name" ON "Badges" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE INDEX "IX_IssueAttachments_IssueId" ON "IssueAttachments" ("IssueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519111416_AddPhase3Infrastructure') THEN
    CREATE INDEX "IX_UserBadges_BadgeId" ON "UserBadges" ("BadgeId");
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522045614_AddIssueStatusHistory') THEN
    CREATE TABLE "IssueStatusHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IssueId" integer NOT NULL,
        "OldStatus" text NOT NULL,
        "NewStatus" text NOT NULL,
        "ChangedByUserId" text,
        "ChangedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueStatusHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueStatusHistories_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522045614_AddIssueStatusHistory') THEN
    CREATE INDEX "IX_IssueStatusHistories_IssueId" ON "IssueStatusHistories" ("IssueId");
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "IssueStatusHistories" ALTER COLUMN "OldStatus" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "IssueStatusHistories" ALTER COLUMN "NewStatus" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ALTER COLUMN "Type" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ALTER COLUMN "Status" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ALTER COLUMN "Severity" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ALTER COLUMN "Priority" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ALTER COLUMN "Frequency" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "Issues" ADD "PainVelocity" double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    ALTER TABLE "IssueComments" ADD "Type" character varying(20) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE TABLE "IssueActivities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IssueId" integer NOT NULL,
        "UserId" text NOT NULL,
        "ActivityType" text NOT NULL,
        "Description" text NOT NULL,
        "Metadata" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueActivities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueActivities_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE TABLE "IssueRelations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IssueId" integer NOT NULL,
        "TargetIssueId" integer NOT NULL,
        "RelationType" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_IssueRelations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IssueRelations_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_IssueRelations_Issues_TargetIssueId" FOREIGN KEY ("TargetIssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_CreatedAt" ON "Issues" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_CreatorUserId" ON "Issues" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_PainScore" ON "Issues" ("PainScore");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_PainVelocity" ON "Issues" ("PainVelocity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_Status" ON "Issues" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_Status_PainScore" ON "Issues" ("Status", "PainScore");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_Status_PainVelocity" ON "Issues" ("Status", "PainVelocity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_Issues_Type" ON "Issues" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_IssueActivities_CreatedAt" ON "IssueActivities" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_IssueActivities_IssueId" ON "IssueActivities" ("IssueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE UNIQUE INDEX "IX_IssueRelations_IssueId_TargetIssueId_RelationType" ON "IssueRelations" ("IssueId", "TargetIssueId", "RelationType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522123237_Phase2OperationalIntelligence') THEN
    CREATE INDEX "IX_IssueRelations_TargetIssueId" ON "IssueRelations" ("TargetIssueId");
    END IF;
END $EF$;


COMMIT;

