CREATE SCHEMA IF NOT EXISTS split;

CREATE TABLE split."SplitGroups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "CreatedByUserId" text NOT NULL,
    "Currency" text NOT NULL DEFAULT 'INR',
    "Status" integer NOT NULL DEFAULT 0,
    "ShareToken" text NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL
);

CREATE UNIQUE INDEX "IX_SplitGroups_ShareToken" ON split."SplitGroups" ("ShareToken");
CREATE INDEX "IX_SplitGroups_CreatedByUserId" ON split."SplitGroups" ("CreatedByUserId");

CREATE TABLE split."SplitGroupMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitGroupId" integer NOT NULL,
    "Name" text NOT NULL,
    "LinkedUserId" text NULL,
    "UpiId" text NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitGroupMembers_SplitGroups_SplitGroupId" FOREIGN KEY ("SplitGroupId") REFERENCES split."SplitGroups" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SplitGroupMembers_SplitGroupId" ON split."SplitGroupMembers" ("SplitGroupId");
CREATE INDEX "IX_SplitGroupMembers_LinkedUserId" ON split."SplitGroupMembers" ("LinkedUserId");

CREATE TABLE split."SplitExpenses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitGroupId" integer NOT NULL,
    "Description" text NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Category" text NULL,
    "SplitType" integer NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitExpenses_SplitGroups_SplitGroupId" FOREIGN KEY ("SplitGroupId") REFERENCES split."SplitGroups" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SplitExpenses_SplitGroupId" ON split."SplitExpenses" ("SplitGroupId");

CREATE TABLE split."SplitExpensePayers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitExpenseId" integer NOT NULL,
    "SplitGroupMemberId" integer NOT NULL,
    "AmountPaid" numeric(18,2) NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitExpensePayers_SplitExpenses_SplitExpenseId" FOREIGN KEY ("SplitExpenseId") REFERENCES split."SplitExpenses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SplitExpensePayers_SplitGroupMembers_SplitGroupMemberId" FOREIGN KEY ("SplitGroupMemberId") REFERENCES split."SplitGroupMembers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_SplitExpensePayers_SplitExpenseId" ON split."SplitExpensePayers" ("SplitExpenseId");
CREATE INDEX "IX_SplitExpensePayers_SplitGroupMemberId" ON split."SplitExpensePayers" ("SplitGroupMemberId");

CREATE TABLE split."SplitExpenseParticipants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitExpenseId" integer NOT NULL,
    "SplitGroupMemberId" integer NOT NULL,
    "ShareAmount" numeric(18,2) NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitExpenseParticipants_SplitExpenses_SplitExpenseId" FOREIGN KEY ("SplitExpenseId") REFERENCES split."SplitExpenses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SplitExpenseParticipants_SplitGroupMembers_SplitGroupMemberId" FOREIGN KEY ("SplitGroupMemberId") REFERENCES split."SplitGroupMembers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_SplitExpenseParticipants_SplitExpenseId" ON split."SplitExpenseParticipants" ("SplitExpenseId");
CREATE INDEX "IX_SplitExpenseParticipants_SplitGroupMemberId" ON split."SplitExpenseParticipants" ("SplitGroupMemberId");

CREATE TABLE split."SplitSettlements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitGroupId" integer NOT NULL,
    "FromMemberId" integer NOT NULL,
    "ToMemberId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Method" integer NOT NULL,
    "UpiIdUsed" text NULL,
    "PaymentReference" text NOT NULL,
    "Status" integer NOT NULL DEFAULT 0,
    "CompletedAt" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitSettlements_SplitGroups_SplitGroupId" FOREIGN KEY ("SplitGroupId") REFERENCES split."SplitGroups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SplitSettlements_SplitGroupMembers_FromMemberId" FOREIGN KEY ("FromMemberId") REFERENCES split."SplitGroupMembers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SplitSettlements_SplitGroupMembers_ToMemberId" FOREIGN KEY ("ToMemberId") REFERENCES split."SplitGroupMembers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_SplitSettlements_SplitGroupId" ON split."SplitSettlements" ("SplitGroupId");
CREATE INDEX "IX_SplitSettlements_FromMemberId" ON split."SplitSettlements" ("FromMemberId");
CREATE INDEX "IX_SplitSettlements_ToMemberId" ON split."SplitSettlements" ("ToMemberId");
