CREATE TABLE split."SplitGroupInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SplitGroupId" integer NOT NULL,
    "CreatedByUserId" text NOT NULL,
    "TokenHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NULL,
    "MaxUses" integer NULL,
    "UsedCount" integer NOT NULL DEFAULT 0,
    "RevokedAt" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_SplitGroupInvites_SplitGroups_SplitGroupId" FOREIGN KEY ("SplitGroupId") REFERENCES split."SplitGroups" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_SplitGroupInvites_TokenHash" ON split."SplitGroupInvites" ("TokenHash");
CREATE INDEX "IX_SplitGroupInvites_SplitGroupId" ON split."SplitGroupInvites" ("SplitGroupId");
