CREATE TABLE accounts."CreditCardPayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" text NOT NULL,
    "CreditCardAccountId" integer NOT NULL,
    "PayingAccountId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "PaymentAppName" text NULL,
    "CashbackAmount" numeric(18,2) NULL,
    "CashbackType" integer NULL,
    "CashbackAccountId" integer NULL,
    "InterestPortion" numeric(18,2) NOT NULL,
    "PrincipalPortion" numeric(18,2) NOT NULL,
    "InterestTransactionId" integer NULL,
    "PrincipalExpenseTransactionId" integer NULL,
    "PrincipalIncomeTransactionId" integer NULL,
    "CashbackTransactionId" integer NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_CreditCardPayments_Accounts_CreditCardAccountId" FOREIGN KEY ("CreditCardAccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CreditCardPayments_Accounts_PayingAccountId" FOREIGN KEY ("PayingAccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CreditCardPayments_CreditCardAccountId" ON accounts."CreditCardPayments" ("CreditCardAccountId");
