START TRANSACTION;

-- Restored: EF Core's idempotent script wraps every single statement below
-- in a check against this table. It must exist (even empty) for those
-- guards to evaluate correctly on a database that has never seen any of
-- these migrations before. Safe to run against production too --
-- CREATE TABLE IF NOT EXISTS is a no-op there since it already exists.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803152434_AddIsLiabilityToAccountCategories') THEN
    ALTER TABLE accounts."AccountCategories" ADD "IsLiability" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803152434_AddIsLiabilityToAccountCategories') THEN

                    UPDATE "accounts"."AccountCategories"
                    SET "IsLiability" = TRUE
                    WHERE "Name" ILIKE '%credit%'
                       OR "Name" ILIKE '%loan%'
                       OR "Name" ILIKE '%emi%'
                       OR "Name" ILIKE '%debt%'
                       OR "Name" ILIKE '%card%';
                
    END IF;
END $EF$;



DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'challenges') THEN
            CREATE SCHEMA challenges;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE TABLE challenges."ChallengeDays" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DayNumber" integer NOT NULL,
        "WeekNumber" integer NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "IsRestDay" boolean NOT NULL,
        "RequiresReflection" boolean NOT NULL,
        "ActionRoute" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_ChallengeDays" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE TABLE challenges."UserChallengeEnrollments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CurrentStreak" integer NOT NULL,
        "LongestStreak" integer NOT NULL,
        "LastActivityDate" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_UserChallengeEnrollments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE TABLE challenges."UserChallengeProgresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ChallengeDayId" integer NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        "ReflectionText" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_UserChallengeProgresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserChallengeProgresses_ChallengeDays_ChallengeDayId" FOREIGN KEY ("ChallengeDayId") REFERENCES challenges."ChallengeDays" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE UNIQUE INDEX "IX_ChallengeDays_DayNumber" ON challenges."ChallengeDays" ("DayNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE UNIQUE INDEX "IX_UserChallengeEnrollments_UserId" ON challenges."UserChallengeEnrollments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE INDEX "IX_UserChallengeProgresses_ChallengeDayId" ON challenges."UserChallengeProgresses" ("ChallengeDayId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803153655_AddChallengeEngineFoundation') THEN
    CREATE UNIQUE INDEX "IX_UserChallengeProgresses_UserId_ChallengeDayId" ON challenges."UserChallengeProgresses" ("UserId", "ChallengeDayId");
    END IF;
END $EF$;


COMMIT;

