ALTER TABLE accounts."AccountCategories" ADD "AccountType" integer NOT NULL DEFAULT 4;

CREATE TABLE accounts."BankAccountDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" integer NOT NULL,
    "InterestRate" numeric,
    "InterestFrequency" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_BankAccountDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BankAccountDetails_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE TABLE accounts."CreditCardDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" integer NOT NULL,
    "CreditLimit" numeric,
    "MinimumDueAmount" numeric,
    "DueDate" timestamp with time zone,
    "StatementClosingDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_CreditCardDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CreditCardDetails_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE TABLE accounts."LoanDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" integer NOT NULL,
    "PrincipalAmount" numeric,
    "InterestRate" numeric,
    "EmiAmount" numeric,
    "TenureMonths" integer,
    "NextEmiDueDate" timestamp with time zone,
    "StartDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_LoanDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LoanDetails_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts."Accounts" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_BankAccountDetails_AccountId" ON accounts."BankAccountDetails" ("AccountId");

CREATE UNIQUE INDEX "IX_CreditCardDetails_AccountId" ON accounts."CreditCardDetails" ("AccountId");

CREATE UNIQUE INDEX "IX_LoanDetails_AccountId" ON accounts."LoanDetails" ("AccountId");
