CREATE TABLE transactions."DecisionJournalEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Reasoning" text NOT NULL,
    "Amount" numeric,
    "DecisionDate" timestamp with time zone NOT NULL,
    "Outcome" text,
    "OutcomeRecordedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_DecisionJournalEntries" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_DecisionJournalEntries_UserId_DecisionDate" ON transactions."DecisionJournalEntries" ("UserId", "DecisionDate");
