START TRANSACTION;
ALTER TABLE transactions."Transactions" ADD "UserId" text;

UPDATE transactions."Transactions" SET "UserId" = 'system' WHERE "UserId" IS NULL;

ALTER TABLE transactions."Transactions" ALTER COLUMN "UserId" SET DEFAULT '';

CREATE TABLE "IssueTaxonomies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "ParentId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueTaxonomies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueTaxonomies_IssueTaxonomies_ParentId" FOREIGN KEY ("ParentId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT
);

CREATE TABLE transactions."Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" text NOT NULL,
    "Tag" text,
    "CancellationUrl" text,
    "RecurringTransactionId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_RecurringTransactions_RecurringTransactionId" FOREIGN KEY ("RecurringTransactionId") REFERENCES transactions."RecurringTransactions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Issues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "CategoryId" integer,
    "SubcategoryId" integer,
    "Severity" text NOT NULL,
    "ImpactsMoney" boolean NOT NULL,
    "FinancialImpactAmount" numeric,
    "Frequency" text NOT NULL,
    "TrustPenalty" integer NOT NULL,
    "Votes" integer NOT NULL,
    "PainScore" double precision NOT NULL,
    "CreatorUserId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Issues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Issues_IssueTaxonomies_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Issues_IssueTaxonomies_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES "IssueTaxonomies" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "IssueComments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssueId" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatorUserId" text,
    "ExpectedBehavior" text,
    "ActualBehavior" text,
    "HasWorkaround" boolean NOT NULL,
    "StructuredMetadata" text,
    "IsHelpful" boolean NOT NULL,
    "IsRootCause" boolean NOT NULL,
    "IsReproConfirmed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueComments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Transactions_UserId" ON transactions."Transactions" ("UserId");

CREATE INDEX "IX_IssueComments_IssueId" ON "IssueComments" ("IssueId");

CREATE INDEX "IX_Issues_CategoryId" ON "Issues" ("CategoryId");

CREATE INDEX "IX_Issues_SubcategoryId" ON "Issues" ("SubcategoryId");

CREATE INDEX "IX_IssueTaxonomies_ParentId" ON "IssueTaxonomies" ("ParentId");

CREATE UNIQUE INDEX "IX_Subscriptions_RecurringTransactionId" ON transactions."Subscriptions" ("RecurringTransactionId");

CREATE UNIQUE INDEX "IX_Subscriptions_UserId_Name" ON transactions."Subscriptions" ("UserId", "Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515074348_AddUserIdToTransaction', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519074920_AddIssueTrackingSystem', '9.0.9');

CREATE TABLE "IssueVotes" (
    "IssueId" integer NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_IssueVotes" PRIMARY KEY ("IssueId", "UserId"),
    CONSTRAINT "FK_IssueVotes_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519080424_AddIssueVotes', '9.0.9');

ALTER TABLE "IssueVotes" ADD "Value" integer NOT NULL DEFAULT 0;

ALTER TABLE "IssueComments" ADD "ParentCommentId" integer;

ALTER TABLE "IssueComments" ADD "Score" integer NOT NULL DEFAULT 0;

CREATE TABLE "CommentVotes" (
    "CommentId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Value" integer NOT NULL,
    CONSTRAINT "PK_CommentVotes" PRIMARY KEY ("CommentId", "UserId"),
    CONSTRAINT "FK_CommentVotes_IssueComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "IssueComments" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_IssueComments_ParentCommentId" ON "IssueComments" ("ParentCommentId");

ALTER TABLE "IssueComments" ADD CONSTRAINT "FK_IssueComments_IssueComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "IssueComments" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519095253_AddCommentVotesAndReplies', '9.0.9');

ALTER TABLE "Issues" ADD "Type" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519102104_AddIssueTypeField', '9.0.9');

ALTER TABLE "Issues" ADD "ClosedAt" timestamp with time zone;

ALTER TABLE "Issues" ADD "ClosedByUserId" text;

ALTER TABLE "Issues" ADD "GitHubIssueUrl" text;

ALTER TABLE "Issues" ADD "IsClosed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Issues" ADD "MilestoneId" integer;

CREATE TABLE "CommentReactions" (
    "CommentId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Emoji" text NOT NULL,
    CONSTRAINT "PK_CommentReactions" PRIMARY KEY ("CommentId", "UserId", "Emoji"),
    CONSTRAINT "FK_CommentReactions_IssueComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "IssueComments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IssueAssignees" (
    "IssueId" integer NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_IssueAssignees" PRIMARY KEY ("IssueId", "UserId"),
    CONSTRAINT "FK_IssueAssignees_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IssueLabels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Color" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueLabels" PRIMARY KEY ("Id")
);

CREATE TABLE "IssueMilestones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text,
    "DueDate" timestamp with time zone,
    "IsClosed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueMilestones" PRIMARY KEY ("Id")
);

CREATE TABLE "IssueLabelAssignments" (
    "IssueId" integer NOT NULL,
    "LabelId" integer NOT NULL,
    CONSTRAINT "PK_IssueLabelAssignments" PRIMARY KEY ("IssueId", "LabelId"),
    CONSTRAINT "FK_IssueLabelAssignments_IssueLabels_LabelId" FOREIGN KEY ("LabelId") REFERENCES "IssueLabels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IssueLabelAssignments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Issues_MilestoneId" ON "Issues" ("MilestoneId");

CREATE INDEX "IX_IssueLabelAssignments_LabelId" ON "IssueLabelAssignments" ("LabelId");

CREATE UNIQUE INDEX "IX_IssueLabels_Name" ON "IssueLabels" ("Name");

ALTER TABLE "Issues" ADD CONSTRAINT "FK_Issues_IssueMilestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES "IssueMilestones" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519103216_AddPhase2Features', '9.0.9');

ALTER TABLE "Issues" ADD "AcknowledgedAt" timestamp with time zone;

ALTER TABLE "Issues" ADD "ResolvedAt" timestamp with time zone;

CREATE TABLE "Badges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IconUrl" text,
    "Color" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Badges" PRIMARY KEY ("Id")
);

CREATE TABLE "IssueAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssueId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "UploadedByUserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueAttachments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserGamificationProfiles" (
    "UserId" text NOT NULL,
    "KarmaScore" integer NOT NULL,
    "ContributorTag" text,
    CONSTRAINT "PK_UserGamificationProfiles" PRIMARY KEY ("UserId")
);

CREATE TABLE "UserBadges" (
    "UserId" text NOT NULL,
    "BadgeId" integer NOT NULL,
    "AwardedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserBadges" PRIMARY KEY ("UserId", "BadgeId"),
    CONSTRAINT "FK_UserBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Badges_Name" ON "Badges" ("Name");

CREATE INDEX "IX_IssueAttachments_IssueId" ON "IssueAttachments" ("IssueId");

CREATE INDEX "IX_UserBadges_BadgeId" ON "UserBadges" ("BadgeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519111416_AddPhase3Infrastructure', '9.0.9');

CREATE TABLE "IssueStatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssueId" integer NOT NULL,
    "OldStatus" text NOT NULL,
    "NewStatus" text NOT NULL,
    "ChangedByUserId" text,
    "ChangedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueStatusHistories_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_IssueStatusHistories_IssueId" ON "IssueStatusHistories" ("IssueId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260522045614_AddIssueStatusHistory', '9.0.9');

ALTER TABLE "IssueStatusHistories" ALTER COLUMN "OldStatus" TYPE character varying(20);

ALTER TABLE "IssueStatusHistories" ALTER COLUMN "NewStatus" TYPE character varying(20);

ALTER TABLE "Issues" ALTER COLUMN "Type" TYPE character varying(20);

ALTER TABLE "Issues" ALTER COLUMN "Status" TYPE character varying(20);

ALTER TABLE "Issues" ALTER COLUMN "Severity" TYPE character varying(20);

ALTER TABLE "Issues" ALTER COLUMN "Priority" TYPE character varying(20);

ALTER TABLE "Issues" ALTER COLUMN "Frequency" TYPE character varying(20);

ALTER TABLE "Issues" ADD "PainVelocity" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "IssueComments" ADD "Type" character varying(20) NOT NULL DEFAULT '';

CREATE TABLE "IssueActivities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssueId" integer NOT NULL,
    "UserId" text NOT NULL,
    "ActivityType" text NOT NULL,
    "Description" text NOT NULL,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueActivities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueActivities_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IssueRelations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssueId" integer NOT NULL,
    "TargetIssueId" integer NOT NULL,
    "RelationType" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueRelations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IssueRelations_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IssueRelations_Issues_TargetIssueId" FOREIGN KEY ("TargetIssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Issues_CreatedAt" ON "Issues" ("CreatedAt");

CREATE INDEX "IX_Issues_CreatorUserId" ON "Issues" ("CreatorUserId");

CREATE INDEX "IX_Issues_PainScore" ON "Issues" ("PainScore");

CREATE INDEX "IX_Issues_PainVelocity" ON "Issues" ("PainVelocity");

CREATE INDEX "IX_Issues_Status" ON "Issues" ("Status");

CREATE INDEX "IX_Issues_Status_PainScore" ON "Issues" ("Status", "PainScore");

CREATE INDEX "IX_Issues_Status_PainVelocity" ON "Issues" ("Status", "PainVelocity");

CREATE INDEX "IX_Issues_Type" ON "Issues" ("Type");

CREATE INDEX "IX_IssueActivities_CreatedAt" ON "IssueActivities" ("CreatedAt");

CREATE INDEX "IX_IssueActivities_IssueId" ON "IssueActivities" ("IssueId");

CREATE UNIQUE INDEX "IX_IssueRelations_IssueId_TargetIssueId_RelationType" ON "IssueRelations" ("IssueId", "TargetIssueId", "RelationType");

CREATE INDEX "IX_IssueRelations_TargetIssueId" ON "IssueRelations" ("TargetIssueId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260522123237_Phase2OperationalIntelligence', '9.0.9');

COMMIT;

